import type { Job } from "./types/Job";

export const demoJobs: Job[] = [
  {
    id: 1,
    title: "Junior Software Developer",
    company: "Tech Company A",
    location: "New York, NY",
    salary: 70000,
    description: "An entry-level position for aspiring software developers.",
    category: "it",
    logo: null,
    status: "wishlist",
  },
  {
    id: 2,
    title: "Cybersecurity Analyst",
    company: "Cybersecurity Firm B",
    location: "San Francisco, CA",
    salary: 80000,
    description:
      "Responsible for monitoring and protecting the organization's network.",
    category: "cybersecurity",
    logo: null,
    status: "wishlist",
  },
  {
    id: 3,
    title: "Frontend Developer",
    company: "Web Agency C",
    location: "Chicago, IL",
    salary: 75000,
    description:
      "Develop and maintain user-facing features using React and TypeScript.",
    category: "it",
    logo: null,
    status: "wishlist",
  },
  {
    id: 4,
    title: "Backend Developer",
    company: "Software Company D",
    location: "Austin, TX",
    salary: 85000,
    description:
      "Design and implement server-side logic and APIs using Node.js.",
    category: "it",
    logo: null,
    status: "applied",
  },
  {
    id: 5,
    title: "Information Security Specialist",
    company: "Security Firm E",
    location: "Seattle, WA",
    salary: 90000,
    description:
      "Implement security measures to protect sensitive data and systems.",
    category: "cybersecurity",
    logo: null,
    status: "applied",
  },
  {
    id: 7,
    title: "DevOps Engineer",
    company: "Cloud Company G",
    location: "Denver, CO",
    salary: 97500,
    description: "Manage and automate infrastructure and deployment processes.",
    category: "it",
    logo: null,
    status: "interviewing",
  },
  {
    id: 8,
    title: "Security Consultant",
    company: "Consulting Firm H",
    location: "Miami, FL",
    salary: 105000,
    description:
      "Provide expert advice on security best practices and risk management.",
    category: "cybersecurity",
    logo: null,
    status: "offers",
  },
  {
    id: 6,
    title: "Full Stack Developer",
    company: "Tech Startup F",
    location: "Boston, MA",
    salary: 80000,
    description:
      "Work on both frontend and backend development using modern technologies.",
    category: "it",
    logo: null,
    status: "archived",
  },
  {
    id: 9,
    title: "Mobile App Developer",
    company: "App Company I",
    location: "Los Angeles, CA",
    salary: 75000,
    description:
      "Develop and maintain mobile applications for iOS and Android platforms.",
    category: "it",
    logo: null,
    status: "rejected",
  },
];
